### ISSUE TITLE
Does not return correct `terrascan-exit-code`

### ISSUE THREAD

**Issue by miped** [yu-iskw/action-terrascan#12]
It looks like the call to `tee` might be swallowing the exit code from terrascan?

See https://github.com/yu-iskw/action-terrascan/blob/main/script.sh#L48

**Comment by yu-iskw** [comment]
@miped Thank you for the feedback. I will investigate the behavior later.

**Comment by yu-iskw** [comment]
@miped I fixed the issue and released the new version including it. Please make sure of your actions.
https://github.com/yu-iskw/action-terrascan/releases/tag/v1.1.1
